import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PCAC Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head><script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script></head> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
